# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    silent: true
    cmds:
      - task -l

  deploy:
    desc: Deploy lab
    silent: true
    cmds:
      - terraform apply -auto-approve
      
  destroy:
    desc: Destroy lab
    silent: true
    cmds:
      - terraform  destroy -auto-approve
      
  plan:
    desc: Show terraform plan
    silent: true
    cmds:
      - terraform plan
      
  kubeconfig:
    desc: Add the cluster to ~/.kube/config
    silent: true
    cmds:
      - aws eks update-kubeconfig --name k8s-lab --alias k8s-lab --region us-east-1
