# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

env:
  AWS_PROFILE: lab

tasks:
  default:
    silent: true
    cmds:
      - task -l

  deploy:
    desc: Deploy lab
    dir: terraform
    silent: true
    cmds:
      - terraform init
      - terraform apply -auto-approve

  destroy:
    desc: Destroy lab
    dir: terraform
    silent: true
    cmds:
      - task: kubeconfig
      - task: delete-ingress
      - task: drain-and-destroy-nodes
      - task: terraform-destroy
      - task: cleanup-orphaned-enis

  plan:
    desc: Show terraform plan
    dir: terraform
    silent: true
    cmds:
      - terraform init
      - terraform plan

  kubeconfig:
    desc: Add the cluster to ~/.kube/config
    silent: true
    cmds:
      - aws eks update-kubeconfig --name k8s-lab --alias k8s-lab --region us-east-1

  argocd-pf:
    desc: Setup local port forwarding to the ArgoCD pod
    silent: true
    cmds:
      - echo http://127.0.0.1:8080
      - kubectl port-forward -n argocd svc/argo-cd-argocd-server 8080:443 > /dev/null

  argocd-password:
    desc: Get the default admin password for ArgoCD
    silent: true
    cmds:
      - kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d

  alb_dns:
    desc: Print out the ALB DNS name
    silent: true
    cmds:
      - echo "http://$(aws elbv2 describe-load-balancers --query 'LoadBalancers[*].DNSName' --output text | grep argocd)"

  delete-ingress:
    desc: Delete the ArgoCD ingress to force the ALB to be deleted
    silent: true
    cmds:
      - terraform -chdir=terraform destroy -target='kubernetes_ingress_v1.argocd' -auto-approve || true
      - kubectl delete ingress -n argocd --all --ignore-not-found=true || true
      - echo "Waiting for ALB resources to be deleted..."
      - sleep 300

  cleanup-orphaned-enis:
    desc: Cleanup orphaned ENIs
    silent: true
    cmds:
      - aws ec2 describe-network-interfaces --filters Name=tag:cluster.k8s.amazonaws.com/name,Values=k8s-lab --query NetworkInterfaces[*].NetworkInterfaceId --output text | xargs -r -n1 aws ec2 delete-network-interface --network-interface-id

  terraform-destroy:
    desc: Destroy the lab infrastructure
    dir: terraform
    silent: true
    cmds:
      - terraform destroy -auto-approve

  drain-and-destroy-nodes:
    dir: terraform
    silent: true
    cmds:
      - kubectl get nodes -o name | xargs -n1 kubectl drain --ignore-daemonsets --delete-emptydir-data --force --grace-period=60 --disable-eviction || true
      - echo "Nodes drained, waiting for VPC CNI cleanup..."
      - sleep 90
      - terraform destroy -target='module.k8s_lab.module.eks[0].module.eks.module.eks_managed_node_group["default"]' -auto-approve