apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fake-api-key
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "k8s-lab-fake-api-key"
        objectType: "secretsmanager"
