apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.24.4
    helm:
      values: |
        tempo:
          ingester:
            lifecycler:
              ring:
                kvstore:
                  store: inmemory
                replication_factor: 1
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces
          extraVolumeMounts:
            - name: tempo-traces
              mountPath: /var/tempo/traces

        extraVolumes:
          - name: tempo-traces
            emptyDir: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
